<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup Label="GoogleTest">
    <GoogleTestSourceDir>$([MSBuild]::NormalizePath('$(MSBuildThisFileDirectory)', '..\..\..\externals\googletest\'))</GoogleTestSourceDir>
    <GoogleTestBuildDir>$(CMakeToolsBuildDir)GoogleTest\</GoogleTestBuildDir>
    <GoogleTestBuildPath>$([MSBuild]::NormalizePath('$(GoogleTestBuildDir)', '.'))</GoogleTestBuildPath>
    <GoogleTestInstallDir>$(CMakeToolsBuildDir)</GoogleTestInstallDir>
    <IncludePath>$(GoogleTestInstallDir)include;$(IncludePath)</IncludePath>
    <GoogleTestLibInstallDir Condition="'$(Configuration)'=='Debug'">$(GoogleTestInstallDir)lib\Debug</GoogleTestLibInstallDir>
    <!-- Release の gtest/gmock は CMake のビルドツリー直下（install が lib\Release にコピーしない） -->
    <GoogleTestLibInstallDir Condition="'$(Configuration)'=='Release'">$(GoogleTestBuildPath)\lib\Release</GoogleTestLibInstallDir>
    <LibraryPath>$(GoogleTestLibInstallDir);$(LibraryPath)</LibraryPath>
    <GTestLibName>gtest.lib</GTestLibName>
    <GTestLibPath>$(GoogleTestLibInstallDir)\$(GTestLibName)</GTestLibPath>
    <GMockLibName>gmock.lib</GMockLibName>
    <GMockLibPath>$(GoogleTestLibInstallDir)\$(GMockLibName)</GMockLibPath>
  </PropertyGroup>
  <!-- LibraryPath だけではリンクが参照しないため、明示的に追加する -->
  <ItemDefinitionGroup Label="GoogleTest.Link">
    <Link>
      <AdditionalLibraryDirectories>$(GoogleTestLibInstallDir);%(AdditionalLibraryDirectories)</AdditionalLibraryDirectories>
    </Link>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Label="GoogleTest.Requirements">
    <ClCompile>
      <PreprocessorDefinitions>_SILENCE_TR1_NAMESPACE_DEPRECATION_WARNING;%(PreprocessorDefinitions)</PreprocessorDefinitions>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup Label="GoogleTest.Libs">
    <Link>
      <AdditionalDependencies>$(GTestLibName);%(AdditionalDependencies)</AdditionalDependencies>
      <AdditionalDependencies>$(GMockLibName);%(AdditionalDependencies)</AdditionalDependencies>
    </Link>
  </ItemDefinitionGroup>
</Project>